### ISSUE TITLE
links need updating on eopas page

### ISSUE THREAD

**Issue by nthieberger** [eopas/eopas#62]
The link on http://www.eopas.org/ to the UniMelb project page [at the School of Language and Linguistics, University of Melbourne, Australia,] is broken, it should now point to http://languages-linguistics.unimelb.edu.au/research/projects-eopas-system

My email contact at the bottom of the page should point to thien@unimelb.edu.au

**Comment by silviapfeiffer** [comment]
Fixed in 8c7f8a792d4fc798c266a4b1ad9ab0d3d6e7fd53 and 1ecb3016724a62c61e99681723738ce30b0259ec
