### ISSUE TITLE
Error in validating elan files

### ISSUE THREAD

**Issue by nthieberger** [eopas/eopas#67]
I want to upload an Elan file to Eopas. It validates fine, both against
 the current Elan schema and against the elan.xsd on the Eopas site. But it
 throws this error in validation during upload.

Source Transcript did not validate against the schema
Source ERROR: Unsupported LINGUISTIC_TYPE_REF in Tier

**Comment by silviapfeiffer** [comment]
Must be a bug in the mapping from Elan to Eopas xslt script. Might be a good idea to have this as a starter for the new developers.
